<?php

namespace Plugin\SSProductDetailPage\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductDetailBlockPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDetailBlockPositionRepository extends EntityRepository
{
}
